copyright = "© StarModel Internacional" 
title = "StarModel Agency"
defaultContentLanguage = "es"
languageCode = "es"
disableLanguages = []

theme = "gallery"

[params]
  defaultTheme = "dark"
  
  title = "StarModel International"
  subtitle = "Agencia de modelos StarModel"
  description = "Los mejores modelos son de la academia StarModel"

  [params.socialIcons]
    facebook = "https://www.facebook.com/starmodelv/"
    instagram = "https://www.instagram.com/starmodelv/"
    website = "https://agenciastarmodel.com/"
    youtube = "https://www.youtube.com/@starmodelagencia3389"
    email = "mailto:starmodel.smi@gmail.com"
    whatsapp = "5491134384433"

  [params.gallery]
    boxSpacing = 10
    targetRowHeight = 288
    targetRowHeightTolerance = 0.25

[menu]
  [[menu.main]]
      identifier = "masc"
      name = "Masculinos"
      url = "/masculinos/"
  [[menu.main]]
      identifier = "fem"
      name = "Femeninos"
      url = "/femeninos/"
  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
  
  [[menu.footer]]
    name = "Sitio web"
    url = "https://agenciastarmodel.com/"
    weight = 3

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
